### ISSUE TITLE
4월 12일 (수) 

### ISSUE THREAD

**Issue by Limdongmoo** [hobbyloop/hobbyloop-be#21]
- 예정된 할일
    - [완료] 멀티모듈 적용
    - [완료] pr trigger 시 빌드만 하도록 변경, secret 문제 해결
    - [진행중] 회원 관련 기능 정의

**Comment by jungminji0215** [comment]
- 예정된 할일
  - [진행중] secret 문제 살펴보기
  - [예정] 회원 가입 API
