### ISSUE TITLE
[기능 구현] 회원용 로그인 구현

### ISSUE THREAD

**Issue by Limdongmoo** [hobbyloop/hobbyloop-be#32]
# 1.회원용 로그인 기능 구현하기
-소셜 로그인만 적용
    - 도메인 : naver, google, kakao, apple (naver 는 안하기로 결정)
    - 남은 작업 : naver 로그인 없애고 apple 로그인 추가하기

---
## 2. 소셜 로그인 시퀀스
1. 사용자가 로그인 요청
2. 프론트엔드(클라이언트) 측에서 백엔드로 OAuth 인가 요청
    - 이 때, 필요한 파라미터와 함께 요청 전달
    - Ex. provider
3. Provider 별로 Authorization Code 인증을 할 수 있도록 리다이렉트
4. 프론트엔드(클라이언트) 에서 사용자에게 로그인 페이지를 보여줌
5. 사용자가 로그인 창에 로그인
6. 로그인이 완료되면 Authorization Server 에서 백엔드로 Authorization 코드 응답
7. 백엔드에서 Authorization Server 에서 받은 인가코드를 이용하여 Authorization Server에 AccssToken 요청
8. 엑세스 토큰 획득
9. 엑세스 토큰을 이용하여 Resource Server 에 유저 데이터 요청
10. 획득한 데이터를 DB 저장 후 JWT 엑세스 토큰과 리프레시 토큰을 생성
11. 리프레시 토큰은 수정 불가능한 쿠키에 저장하고 엑세스 토큰은 프론트엔드 리다이렉트 URI 에 쿼리스트링에 코튼을 담아 리다이렉트
12. 프론트에서 토큰 저장 후 요청시 헤더에 Authroization: Bearer{token} 을 추가하여 요청
13. 백엔드에서는 토큰을 확인하여 권한 확인
14. 토큰 만료 후 쿠키에 저장된 리프레시 토큰을 이용하여 엑세스 토큰과 리프레시 토큰을 재발급

---
## 3. 필요한 값들
hobbyloop-api/src/main/java/hobbyloop/backend/api 의 application-secret.yml
(현재 github.secrets 로 정의되어 빌드 시에 생성되는 파일) 에 정리

---
### 1. MultiModule 에서 implementation 으로 참조하지 못하는 에러
```
Parameter 0 of constructor in hobbyloop.backend.domain.user.UserService required a bean of type
'hobbyloop.backend.domain.user.UserRepository' that could not be found.
```
- domain 모듈에 위치한 UserRepository 를 bean 으로 등록하지 못함
- Application 의 basePackage 를 설정해서 bean 으로 등록할 수 있도록 수정

### To be
```
@SpringBootApplication
@ComponentScan(basePackages = {"hobbyloop.backend.domain","hobbyloop.backend.api"})
@EnableJpaRepositories(basePackages = "hobbyloop.backend.domain")
@EntityScan("hobbyloop.backend.domain")
@EnableJpaAuditing
public class HobbyloopApiApplication {
    public static void main(String[] args) {
        SpringApplication.run(HobbyloopApiApplication.class, args);
    }
}
```

### 2. Database 에 Token 이 저장되지 않는 에러
```
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column
```
- JWT 로 토큰 생성 후 저장 과정에서 저장이 되지 않음
- Spring boot 에서 String 자료형으로 선언 시 MySQL 에서는 VARCHAR(255) 로 설정이 되지만 토큰의 문자열 길이가 너무 길어서 저장이 되지 않음
- Spring boot 에서는 String 으로 선언하지만 MySQL 에서 저장될 때 TEXT 타입으로 저장될 수 있도록 설정 변경

### As is
```
    private String accessToken;
    private String refreshToken;
```
### To be
```
    @Column(columnDefinition="TEXT")
    private String accessToken;
    @Column(columnDefinition="TEXT")
    private String refreshToken;
```
---
## 5. 구현 내용
- 참고한 내용
   - github : https://github.com/sh111-coder/oauth2WithJwtLogin
   - 강의 : https://www.inflearn.com/course/%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8-%EC%8B%9C%ED%81%90%EB%A6%AC%ED%8B%B0/dashboard

- 구현 내용
### 1. 로그인 시퀀스
>1.1. 로그인 요청 (구글, 카카오, 네이버)
>1.2. 각 로그인 플랫폼으로 이동
>1.3. 해당 플랫폼에서 로그인
>1.4. 로그인 한 유저의 정보를 바탕으로 JWT 토큰 발급
>1.5. JWT 토큰을 헤더에 담아서 전달
>>1.5-1. access token header name : `Authorization`
>>1.5-2. refresh token header name : `Authorization-refresh`
>>1.5-3. value : Bearer + "token"

>6. 로그인 완료

### 2. 토큰 생성
>2.1 사용자 로그인 시 email 생성 ( 플랫폼에서 이메일과 비밀번호를 입력하여 로그인을 하지 않기 떄문에 임의대로 생성)
>>2.1-1 사용자 로그인시 UUID 로 중복없는 문자열 생성 + @socialUser.com
>>2.1-2 난수를 조합하여 비밀번호 임의 생성

>2.2 생성된 이메일을 기반으로 jwt 토큰 생성

**Comment by xonmin** [comment]
>1. MultiModule 에서 implementation 으로 참조하지 못하는 에러
```
Parameter 0 of constructor in hobbyloop.backend.domain.user.UserService required a bean of type
'hobbyloop.backend.domain.user.UserRepository' that could not be found.
```
> domain 모듈에 위치한 UserRepository 를 bean 으로 등록하지 못함
> Application 의 basePackage 를 설정해서 bean 으로 등록할 수 있도록 수정

domain 모듈 내에 위치한 bean에서 동일 모듈에 위치한 bean 을 찾지 못하는 건 이해가 안되네요..ㅠ 
이유가 뭘까요

**Comment by Limdongmoo** [comment]
처음에는 bean 등록을 잘못했다고 생각했는데 어디가 잘못된건지 잘 모르겠어서

처음에는 api 모듈의 Application 에서 UserService bean을 찾지 못해서 
@ComponentScan(basePackages = {"hobbyloop.backend.domain","hobbyloop.backend.api"})
이 어노테이션으로 컴포넌트 스캔 basePackage를 설정해줬는데 
그 이후에는 Repository bean 탐색이 안돼서 생각해보니까 
Application 에서 bean 을 찾지 못해서 모듈의 경로를 지정해줬으면 마찬가지로 JpaRepository 도 경로를 지정해줘야 할 것 같다고 생각했습니다

그래서
@EnableJpaRepositories(basePackages = "hobbyloop.backend.domain")
이 어노테이션으로 Jpa Repository 경로를 지정해주니 해결이 되었습니다

**Comment by Limdongmoo** [comment]
현재 고려해야 할 사항들
1. User.ROLE 이 최초 로그인 시 GUEST 로 설정되어 있음
    - 이후 추가 정보를 기입하는 요청을 통해서 GUEST 에서 USER 로 변환하는 요청 생성
    
2. 로컬 로그인은 사용하지 않기 때문에 관련된 내용 수정하기
    - LoginSuccessHandler, FailureHandler 등
    - SecurityConfig 또한 수정 필요

**Comment by Limdongmoo** [comment]
+ 현재 로그인 플랫폼 내에서 리다이렉트 ip 가 로컬로 되어있음
배포시 사용할 수 있도록 배포용 생성하여 배포되어있는 프로젝트의 client-id 및 secret 변경해주기
