### ISSUE TITLE
4월 24일 (월)

### ISSUE THREAD

**Issue by Limdongmoo** [hobbyloop/hobbyloop-be#38]
🔔 4월 12일 weekly scrum 업데이트 해주세요~

**Comment by Limdongmoo** [comment]
- 예정된 할일
    - [진행중] 회원 관련 기능 정의
        - [진행중] 로그인 기능 수정 마무리
        - [예정] 회원관리 기능 구현하기
    - [예정] 회원용 MVP 모델에 포함될 기능 생각하기

**Comment by jungminji0215** [comment]
프로필 등록 API 먼저 하려고했으나..  회의 결과 소셜 로그인 먼저 하기로 함.
- 예정된 할일
  * [ ] 소셜 로그인 기능 개발
    * [ ] 구글
    * [ ] 카카오
    * [ ] 애플
