### ISSUE TITLE
[기능구현] 프로필 등록기능

### ISSUE THREAD

**Issue by Limdongmoo** [hobbyloop/hobbyloop-be#41]
## 프로필 등록 기능
---
- 사용자가 최초 로그인 시 User.Role -> Role.GUEST 로 설정되어 있음
- 최초 로그인 이후 프로필 등록 페이지로 이동하여 사용자가 프로필을 등록하면
    1. 사용자의 프로필 정보를 DB에 저장
    2. 사용자의 역할을 수정(이후 강사, 업체 등에서도 마찬가지로 Role 을 수정할 것 같아서 Role 을 파라미터로 전달하여 변경)

---
## Issue
- 하나의 요청에서 두 도메인의 기능이 필요한 경우 (위의 상황에서는 
    - 1. 프로필 등록 (UserProfile 도메인)
    - 2. User.Role 변경 (User 도메인) 으로 두 도메인에 대한 접근)
- UserProfileApplicationService 에서 이번에 정의한 것 처럼 UserService 에 직접 메시지를 전달하여 처리하는지
- UserServiceApplication 에 메시지를 전달하여 UserServiceApplication 이 UserService 에 메시지를 전달하여 처리하는건지 궁금합니다

ApplicationService 가 Controller 에서의 요청을 다른 모듈인 domain 모듈에 전달하기 위한 매체로 ApplicationService 에서 여러 Service 에 대한 의존성을 가지고 있는 것이 자연스럽다고는 생각하지만
한편으로는 `각 Service 에 대한 메시지 전달` 이라는 책임이 각 ApplicationService 에 부여되어 있기 때문에 ApplicationService 에게 메시지를 전달하는 것이 한 개의 플로우가 추가되지만 맞는 방법일 수도 있겠다라는 생각이 들어서 질문합니다

**Comment by xonmin** [comment]
딥하게 가면, 바운디드 컨텍스트와 애그리게이트를 어떻게 설정하느냐에 따라 다른데, 

동일한 계층간에서 횡간 호출은 좋지 않습니다. (의존성 문제가 꼬일 수 있습니다)  
말씀하신대로 클래스간의 책임을 따지는 측면에서는 맞는 방법으로 보이지만, 그 외의 문제들이 많기 때문에 
이 때는 `User` 라는 도메인의 비즈니스 로직은 `UserService`가 담당하는 것과 레이어 측면에서의 호출로 보면 
저도  `UserProfileApplicationService` 에서 `UserService` 를 호출해서 처리할 것 같습니다.

이 때 transaction 범위와 정합성에도 유의하면 좋을 것 같습니다.

**Comment by Limdongmoo** [comment]
> 읽어보면서 궁금한게 생겼는데, 그러면 ERD 상에서 프로필 내 테이블에는 ROLE 정보가 존재하나요?

아뇨 존재하지 않아요
그래서 UserService 를 의존성 주입 받아서 UserService 에서 User.Role 을 변경하는 로직을 통해서 구현했습니다
그러면 현재 구현한 방식처럼 다른 도메인의 Service 를 직접 주입받아서 사용하는 방식으로 구현하겠습니다~
